### ISSUE TITLE
I need source of data / 데이터의 출처가 궁금합니다

### ISSUE THREAD

**Issue by ghost** [gs97ahn/c_subway_navigation#1]
Are the whole data created by you or is there any source?

데이터의 출처가 있을까요? 아니면 직접 만드신 건가요?

**Comment by nogamsung** [comment]
안녕하세요!
프로젝트에 데이터는 과제를 수행하기 위해 제 교수님께서 제공 해주셨습니다.

**Comment by ghost** [comment]
저희는 현재 대회 참가를 위한 팀 프로젝트를 준비 중입니다. 이를 위해 이 데이터가 꼭 필요해서 출처가 필요했습니다. 혹시 이 데이터를 대회 참가를 목적으로 사용해도 될까요?

**Comment by nogamsung** [comment]
아마 지하철 정보는 공공데이터이기 때문에 괜찮을거 같습니다.
다만 지하철 노선과 시간이 최신 데이터가 아닌거 인지해주세요!

최신 데이터는 [서울시 공공데이터](https://data.seoul.go.kr/dataList/datasetList.do?datasetKind=1&searchFlag=M)에서 [서울교통공사 역간 거리 및 소요시간 정보](https://data.seoul.go.kr/dataList/OA-12034/S/1/datasetView.do)과 같은 정보도 찾을 수 있습니다.

**Comment by ghost** [comment]
넵, 감사합니다!
